package com.mycompany.estela_raton;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author samus
 */
public class MainFrame extends javax.swing.JFrame {

    private static final int MILISECONDS_BETWEEN_MOUSE_EVENTS = 20;
    
    private int background;
    private int trail;
    private long lastRecordedPointTime;
        
    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
        updateBackgroundColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundLabel = new javax.swing.JLabel();
        trailLabel = new javax.swing.JLabel();
        backgroundComboBox = new javax.swing.JComboBox<>();
        trailComboBox = new javax.swing.JComboBox<>();
        lienzo = new com.mycompany.estela_raton.Lienzo();
        jonayLabel = new javax.swing.JLabel();
        samuelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estela de ratón");

        backgroundLabel.setText("Color del fondo:");

        trailLabel.setText("Color de la estela");

        backgroundComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Azul", "Rojo", "Negro" }));
        backgroundComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundComboBoxActionPerformed(evt);
            }
        });

        trailComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Blanco", "Azul", "Rojo" }));
        trailComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trailComboBoxActionPerformed(evt);
            }
        });

        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        jonayLabel.setText("Jonay Suárez Ramírez");

        samuelLabel.setText("Samuel Trujillo Santana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jonayLabel)
                                .addGap(18, 18, 18)
                                .addComponent(samuelLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backgroundLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(trailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trailComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jonayLabel)
                    .addComponent(samuelLabel))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundLabel)
                    .addComponent(trailLabel)
                    .addComponent(backgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trailComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundComboBoxActionPerformed
        updateBackgroundColor();
    }//GEN-LAST:event_backgroundComboBoxActionPerformed

    private void trailComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trailComboBoxActionPerformed
        updateTrailColor();
    }//GEN-LAST:event_trailComboBoxActionPerformed

    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved
        long eventTime = evt.getWhen();
        if (eventTime - lastRecordedPointTime < MILISECONDS_BETWEEN_MOUSE_EVENTS){
            return;
        }
        this.lastRecordedPointTime = eventTime;
        int posx = evt.getX();
        int posy = evt.getY();
        this.lienzo.updateTrail(posx, posy);
    }//GEN-LAST:event_lienzoMouseMoved


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                    javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> backgroundComboBox;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel jonayLabel;
    private com.mycompany.estela_raton.Lienzo lienzo;
    private javax.swing.JLabel samuelLabel;
    private javax.swing.JComboBox<String> trailComboBox;
    private javax.swing.JLabel trailLabel;
    // End of variables declaration//GEN-END:variables

    private void updateBackgroundColor() {
        background = this.backgroundComboBox.getSelectedIndex();
        Color color = Color.WHITE;
        switch(background){
            case 0:
                color = Color.WHITE;
                break;
            case 1:
                color = new Color(82, 168, 255); //Light blue
                break;
            case 2:
                color = new Color(255, 128, 128); //Light red
                break;
            case 3:
                color = Color.BLACK;                
                break;
        }
        this.lienzo.updateBackgroundColor(color);
    }

    private void updateTrailColor() {
        trail = this.trailComboBox.getSelectedIndex();
        Color color = Color.BLACK;
        switch(trail){
            case 0:
                color = Color.BLACK;
                break;
            case 1:
                color = Color.WHITE;
                break;
            case 2:
                color = new Color(82, 168, 255); //Light blue
                break;
            case 3:
                color = new Color(255, 128, 128); //Light red
                break;
        }
        
        this.lienzo.updateTrailColor(color);
    }
}
